import type { Deal } from "./types";

// Seed inventory so the UI is fully working before the database is wired in.
// Images use deterministic placeholders (picsum) keyed by slug.
function img(slug: string, n: number) {
  return `https://picsum.photos/seed/${slug}-${n}/1200/800`;
}

export const SEED_DEALS: Deal[] = [
  {
    id: "1",
    slug: "18700-nw-44th-ct-miami-gardens-fl",
    address: "18700 NW 44th Ct",
    city: "Miami Gardens",
    state: "FL",
    zip: "33055",
    lat: 25.9412,
    lng: -80.2456,
    beds: 4,
    baths: 2,
    sqft: 1980,
    purchasePrice: 479900,
    entryFee: 65000,
    interestRate: 4.5,
    monthlyPayment: 2890,
    dealTypes: ["Seller Finance", "Subto"],
    status: "available",
    featured: true,
    description:
      "Turnkey single-family in a high-demand Miami Gardens pocket. Existing low-rate mortgage makes this an ideal subject-to or seller-finance acquisition with strong monthly cash flow as a long-term rental.",
    images: [img("18700-nw-44th-ct-miami-gardens-fl", 1), img("18700-nw-44th-ct-miami-gardens-fl", 2), img("18700-nw-44th-ct-miami-gardens-fl", 3)],
    published: true,
    createdAt: "2026-05-28",
  },
  {
    id: "2",
    slug: "1829-caribbean-view-ter-kissimmee-fl",
    address: "1829 Caribbean View Ter",
    city: "Kissimmee",
    state: "FL",
    zip: "34747",
    lat: 28.3105,
    lng: -81.5897,
    beds: 9,
    baths: 7,
    sqft: 4120,
    purchasePrice: 872500,
    entryFee: 65000,
    interestRate: 7.5,
    monthlyPayment: 5950,
    dealTypes: ["STR", "Furnished", "Hybrid"],
    status: "available",
    featured: true,
    description:
      "Fully furnished resort-area short-term rental minutes from Disney. Proven Airbnb income history. Hybrid seller-finance terms available with a manageable entry fee for an instantly cash-flowing STR.",
    images: [img("1829-caribbean-view-ter-kissimmee-fl", 1), img("1829-caribbean-view-ter-kissimmee-fl", 2), img("1829-caribbean-view-ter-kissimmee-fl", 3)],
    published: true,
    createdAt: "2026-05-30",
  },
  {
    id: "3",
    slug: "4412-s-honore-st-chicago-il",
    address: "4412 S Honore St",
    city: "Chicago",
    state: "IL",
    zip: "60609",
    lat: 41.8136,
    lng: -87.6722,
    beds: 3,
    baths: 1,
    sqft: 1340,
    purchasePrice: 189000,
    entryFee: 18900,
    dealTypes: ["Cash", "Fix & Flip"],
    status: "available",
    description:
      "Cash-only fixer in an appreciating Back of the Yards corridor. Solid bones, cosmetic rehab. Comps support a strong ARV for a quick flip or BRRRR. Repair estimate and comps available on request.",
    images: [img("4412-s-honore-st-chicago-il", 1), img("4412-s-honore-st-chicago-il", 2)],
    published: true,
    createdAt: "2026-06-01",
  },
  {
    id: "4",
    slug: "2207-e-cesar-chavez-st-austin-tx",
    address: "2207 E Cesar Chavez St",
    city: "Austin",
    state: "TX",
    zip: "78702",
    lat: 30.2596,
    lng: -97.7204,
    beds: 5,
    baths: 4,
    sqft: 2600,
    purchasePrice: 749000,
    entryFee: 90000,
    interestRate: 5.25,
    monthlyPayment: 4100,
    dealTypes: ["Co-Living", "MTR", "Novation"],
    status: "under_contract",
    description:
      "East Austin co-living / mid-term rental play with five private suites. Novation structure in place. Walkable to downtown with steady traveling-professional demand.",
    images: [img("2207-e-cesar-chavez-st-austin-tx", 1), img("2207-e-cesar-chavez-st-austin-tx", 2)],
    published: true,
    createdAt: "2026-05-20",
  },
  {
    id: "5",
    slug: "915-magnolia-ave-atlanta-ga",
    address: "915 Magnolia Ave NW",
    city: "Atlanta",
    state: "GA",
    zip: "30314",
    lat: 33.7592,
    lng: -84.4151,
    beds: 4,
    baths: 3,
    sqft: 2150,
    purchasePrice: 325000,
    entryFee: 25000,
    interestRate: 3.875,
    monthlyPayment: 2150,
    dealTypes: ["Subto", "Lease Purchase"],
    status: "available",
    description:
      "Renovated Westside bungalow with an assumable-style low rate via subject-to. Lease-purchase exit available. Strong rent-to-price ratio in a rapidly improving neighborhood.",
    images: [img("915-magnolia-ave-atlanta-ga", 1), img("915-magnolia-ave-atlanta-ga", 2)],
    published: true,
    createdAt: "2026-06-02",
  },
  {
    id: "6",
    slug: "330-w-julian-st-san-jose-ca",
    address: "330 W Julian St",
    city: "San Jose",
    state: "CA",
    zip: "95110",
    lat: 37.3382,
    lng: -121.9,
    beds: 6,
    baths: 4,
    sqft: 3000,
    purchasePrice: 1450000,
    entryFee: 180000,
    interestRate: 6.0,
    monthlyPayment: 7600,
    dealTypes: ["Seller Finance", "Hybrid"],
    status: "available",
    description:
      "Large multi-suite property near downtown San Jose. Seller open to creative hybrid financing to defer capital gains. Excellent value-add and house-hack potential in a supply-constrained market.",
    images: [img("330-w-julian-st-san-jose-ca", 1), img("330-w-julian-st-san-jose-ca", 2)],
    published: true,
    createdAt: "2026-05-15",
  },
  {
    id: "7",
    slug: "78-edgewater-dr-cleveland-oh",
    address: "78 Edgewater Dr",
    city: "Cleveland",
    state: "OH",
    zip: "44102",
    lat: 41.4861,
    lng: -81.7353,
    beds: 3,
    baths: 2,
    sqft: 1500,
    purchasePrice: 129000,
    entryFee: 12900,
    dealTypes: ["Cash"],
    status: "closed",
    description:
      "Cash-flowing turnkey rental near Edgewater Park. Already tenant-occupied at market rent. Clean title, fast close. (This deal is closed — shown as a track record example.)",
    images: [img("78-edgewater-dr-cleveland-oh", 1)],
    published: true,
    createdAt: "2026-04-30",
  },
  {
    id: "8",
    slug: "612-w-glenn-st-phoenix-az",
    address: "612 W Glenn St",
    city: "Phoenix",
    state: "AZ",
    zip: "85021",
    lat: 33.5512,
    lng: -112.0843,
    beds: 4,
    baths: 2,
    sqft: 1760,
    purchasePrice: 410000,
    entryFee: 40000,
    interestRate: 4.25,
    monthlyPayment: 2500,
    dealTypes: ["Subto", "STR"],
    status: "available",
    featured: true,
    description:
      "North-central Phoenix home with a low fixed rate, perfect for a subject-to STR conversion. City permits STR in this zone. High nightly demand during spring training and winter snowbird season.",
    images: [img("612-w-glenn-st-phoenix-az", 1), img("612-w-glenn-st-phoenix-az", 2)],
    published: true,
    createdAt: "2026-06-03",
  },
];
